name: Run DragonCity Bot
on:
  workflow_dispatch:
    inputs:
      cookie_input:
        description: '1. Nhập Cookie của tài khoản:'
        required: true
        type: string
      userid_input:
        description: '2. Nhập ID đăng nhập GMH (Chuỗi chữ số vd: c65a23...):'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run Script
      env:
        MY_COOKIE: ${{ github.event.inputs.cookie_input }}
        MY_USER_ID: ${{ github.event.inputs.userid_input }}
      run: |
        cat << 'EOF' > bot.py
        import time, requests, random, os
        url = "https://gamemodshub.com/game/dragoncity/script/packet"
        user_id = os.environ.get("MY_USER_ID")
        cookie = os.environ.get("MY_COOKIE")
        
        session = requests.Session()
        session.headers.update({"Cookie": cookie, "User-Agent": "Mozilla/5.0"})
        dem = 0
        loi_lien_tiep = 0
        
        while True:
            if loi_lien_tiep >= 10:
                print("Bot dừng chạy do dính lỗi liên tiếp quá 10 lần (Có thể hết hạn Cookie)!", flush=True)
                break
                
            try:
                res = session.post(url, data={"user_id": user_id, "cmds": "auto-gold-and-xp-50k", "verify": "true"})
                if "Success" in res.text:
                    dem += 1
                    loi_lien_tiep = 0  # Reset nếu thành công
                    print(f"Lượt {dem} thành công", flush=True)
                else:
                    loi_lien_tiep += 1
                    print(f"Lỗi (Lần {loi_lien_tiep}/10): {res.text[:30]}", flush=True)
            except Exception as e:
                loi_lien_tiep += 1
                print(f"Lỗi kết nối (Lần {loi_lien_tiep}/10): {e}", flush=True)
                time.sleep(30)
                continue
                
            time.sleep(random.uniform(14, 15))
        EOF
        python bot.py
